eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: Restaurant-Service

server:
  port: 8102